### ISSUE TITLE
Current status

### ISSUE THREAD

**Issue by MrArtemSid** [dslul/Samsung-NP350V5C-coreboot#1]
What works, what doesn't?

**Comment by dslul** [comment]
Never tried actually, so I'm not sure. But if it boots, almost
everything should be ok

**Comment by MrArtemSid** [comment]
I'm thinking to buy ch341a and try, but i doubt that external gpu would work. Btw, do u still have that laptop?

**Comment by dslul** [comment]
Yes, I'm still using it, it's been my main pc since 2012 :) That's the
reason I've been hesitant to try

**Comment by MrArtemSid** [comment]
Hehe, that laptop is nice tho, especially on Linux, but i faced hw issue after some years. Laptop starts very long (blank black screen with backlight off. Bios waits something or idk) from 10 mins to 2 hours. Meanwhile wake up or reboot time is quick. Only cold boot is long. Ig that's clocker issue. I thought maybe coreboot can solve that somehow so I wouldn't need to remove clocker or to change it

**Comment by MrArtemSid** [comment]
How do u think, is it hard to port coreboot to 8i915md-g?

**Comment by dslul** [comment]
I had that happen to me, solved with a bios reflash. I remember using
afulnx with the 6MiB file extracted from the official samsung bios
firmware update.

**Comment by MrArtemSid** [comment]
Thanks for idea, I'll try

**Comment by MrArtemSid** [comment]
I tried to flash/read stock bios by afudos/afuwin, it just freezes. Didn't try afulnx yet, cause it required ancient linux kernel

**Comment by dslul** [comment]
Do you have the correct bios image?

**Comment by MrArtemSid** [comment]
Yes. Afuwin/afudos can't even backup bios. Just freezes too

**Comment by dslul** [comment]
That's strange. No error messages? It just freezes? If that's the case,
I guess the only thing left is a hardware flash.

**Comment by MrArtemSid** [comment]
Yeah, no error messages

**Comment by MrArtemSid** [comment]
@dslul I have ability to check coreboot, redo if u want
